### PR TITLE
More languages, nesting, regex patterns

### PR DESCRIPTION
**Pull request by swift502**
Hi!

I've been looking into this for a few days, and I wonder what you think. I've made some big changes, and I don't want to force it on you, this is your repository after all, and I don't even know what the direction of the project is. I saw your blog post on http://www.santacodes.com/. Maybe you wanted to implement these things yourself and write about the process or something, I don't know.

So feel free to turn me down if you don't like this PR. I can always make my own extension and do "crazy regex stuff" in my own project. 🙂

## The current state
 This branch supports 23 languages, using VSCode's regex expressions (found directly [in the source code](https://github.com/microsoft/vscode/search?p=2&q=folding+markers+start+end&unscoped_q=folding+markers+start+end)) to recognize region starts and ends. We're using the exact VSCode expressions here, so what can be folded should be exactly the same that's displayed in the Region Viewer.

In short, there's a [json file](https://github.com/swift502/vscode-region-viewer/blob/nesting/santacodes-region-viewer/src/markers.json) with regex definitions for each language. If the current file language is on the list, it looks for region markers. This approach feels very organised, easily expandable, and performance friendly.

## The issue

The major issue is that this new approach does not currently read region names. Instead, the entire region definition is displayed. See image, Javascript, CSharp and HTML:

image

Instead of always displaying a clean `# Level 1` or `# Region 1`

## My questions for you

1. How important are the pretty region names? We can add "pretty region names" for all languages (using named Regex groups, I tried it and it works), but it will take a lot of time, because I'm not at all familiar with the syntax of about half of the languages on the list. It will take time to properly test it so there's no syntax errors for each language. Or we can let the community implement the languages they use. What do you think?

2. Did you even want to support 23 languages? Maybe it's an overkill for you?

3. Do you like my nesting implementation? Did you even plan on implementing nesting?

Thank you for your time.

### CODE REVIEW

**Comment by berabue** [comment]
1. I think the legibility is improved if the region name is pretty. The user knows that it is an extension that distinguishes regions, so I do not need to print unnecessary syntax.

2. My first intention was for me, so I supported C# which I mainly use. However, I think it is better to support more languages ​​in order to be a program used by many people.

3. I like the nesting features you have implemented!


I am not sure if my intentions are being communicated properly because of my lack of English proficiency.

**Comment by swift502** [comment]
Yes I understand. 🙂 

Fantastic. I'll start working on adding the pretty region names to all languages. Like I said, I don't know how long it'll take though.

**Comment by swift502** [comment]
VB is a bit strange. Folding works when a line starts with #Region, but as far as I can tell, a region name must be supplied and I need to escape the double quotes to strip them.

image

So right now, there's a difference between what can be folded and what is displayed in VB. But I don't think in practice it should be a problem.

**Comment by swift502** [comment]
I can't completely transfer Java.

Java has editor folds which a) are not regions, b) I don't know how to escape them.
It still has regular region markers, so I propose editor folds won't be displayed in our region viewer. It even makes sense I think.

```
// <editor-fold defaultstate="collapsed" desc=" $DESCRIPTION$ ">
// </editor-fold>
```

**Comment by swift502** [comment]
That was easier than I thought. 😄 
Tell me if you have any objections.

If not you can probably merge. 👍

**Comment by swift502** [comment]
Ok I also removed the =pod and =cut markers from Perl. They're apparently just multi-line comments. It makes sense for them to be folded, but they can't be used as regions, since you can't put code inside, only comments.

**Comment by swift502** [comment]
Thanks! 🎉

**Pull request merged**
